@startuml  

title:上传端类图

class tkinter.Canvas {
    +create_line()
}

class Launch.main {
    +Canvas cv
    +setGUI():None
    file_analysis(self, filename)
}

package Launch {

    tkinter.Tk <|-- Launch.main : 泛化
    tkinter.Canvas --* Launch.main : 组合
}

package Tl_main <<Frame>> {
    Tl_nnp : +editPath(self):None
    Tl_nnp : +okFunc(self):None
    
    tkinter.Frame <|-- Tl_nnp : 泛化
    tkinter.Frame <|-- Tl_TasksView : 泛化

    Launch.main -> Tl_TasksView: 关联
    Launch.main --> Tl_nnp: 关联
}

package TL_TaskView <<Frame>> {
    Tl_TasksView --> Tl_TaskView :关联
    tkinter.Frame <|-- Tl_TaskView : 泛化

}



@enduml